language: scala
scala:
  - 2.11.7
jdk:
  - oraclejdk8
env:
  - CODACY_PROJECT_TOKEN=c77729ea848d41529e513607e45dfe96
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  - sbt coverageReport
  - sbt codacyCoverage
  