site_name: akka-wamp-master
site_author: Paolo Angioletti
repo_name: https://github.com/angiolep/akka-wamp
theme: readthedocs  
pages:
  - Home: 'index.md'
  - Router: 'router.md'
  - Client:
    - 'Actor based API': 'client/actor.md'
    - 'Future based API': 'client/future.md'
    - 'Stream based API': 'client/stream.md'
    - 'Configuration': 'client/config.md'
  - Messages: 'messages.md'  
