site_name: akka-wamp-master
site_author: Paolo Angioletti
repo_name: https://github.com/angiolep/akka-wamp
theme: readthedocs
pages:
  - Home: 'index.md'
  - Router: 'router.md'
  - Client:
    - 'Actor based API': 'client/actor.md'
    - 'Future based API':
      - 'Overview': 'client/future/overview.md'
      - 'Session Handling': 'client/future/session.md'
      - 'Publish and Subscribe': 'client/future/pubsub.md'
      - 'Remote Procedure Calls': 'client/future/rpc.md'
      - 'Payload Handling': 'client/future/payload.md'
    - 'Stream based API': 'client/stream.md'
    - 'Configuration': 'client/config.md'
  - Messages: 'messages.md'  
